### ISSUE TITLE
[Tabs] Tabs stack vertically instead of horizontally

### ISSUE THREAD

**Issue by econic** [matsp/material-components-vue#322] opened 2019-07-01 11:47 UTC
**Describe the bug**
Taking the tabs component straight from the documentation an using it in your example-pin, the tabs stack vertically. Can't find a cause or fix.

**To Reproduce**
Use as in the documentation

**Expected behavior**
Should stack horizontally

**Example**
https://codepen.io/econic/pen/ZdxGGJ

**Comment by tychenjiajun** [comment] 2019-07-01 11:49
Fixed in #313

**Comment by tychenjiajun** [comment] 2019-07-01 11:51
This issue seems like a duplicate of #312

**Comment by tychenjiajun** [comment] 2019-07-02 06:11
After checking the codepen again, I can confirm that this issue is fixed.

**Closed by tychenjiajun** 2019-07-02 06:11 UTC
