### ISSUE TITLE
[TextField] valid prop not working as expected

### ISSUE THREAD

**Issue by ktmellow** [matsp/material-components-vue#323] opened 2019-07-01 22:39 UTC
**Describe the bug**
TextField seems valid after editing and clicking out. This is true even when TextField has hardcoded prop :valid="false".

**To Reproduce**
1. Go to material-components-vue component demo
2. Click to uncheck checkbox for 'valid'. Component now has hardcoded invalid field.
3. Click into any TextField, enter new value, and click out.
4. TextField no longer seems 'invalid'. (Class mdc-text-field--invalid not applied)

**Expected behavior**
TextField should appear invalid as long as component has :valid="false"

**Desktop (please complete the following information):**
 - Device:  Chrome 75 on macOS (High Sierra)

**Comment by ktmellow** [comment] 2019-07-02 00:01
:useNativeValidation="false" seems to correct the issue. Changing useNativeValidation default to false may be the fix needed... unless it was default true for a good reason.

**Comment by tychenjiajun** [comment] 2019-07-02 01:59
Well, I think the default value of `useNativeValidtion` should be true because it's default true in [mdc-web](https://github.com/material-components/material-components-web/blob/master/packages/mdc-textfield/foundation.ts) and the native input without any framework also [use default native validation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text#Input_value_length).

So I think the expected behaviour should be ignoring the `valid` property when `useNativeValidation` is true. The [ValidityState in Web API](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState) is also read-only.

**Comment by tychenjiajun** [comment] 2019-07-15 02:24
English isn't my first language, so please excuse any mistakes.

I think the expected behaviour of `<m-text-field>` should be complete the same as `<input type="text">`. That is, the `useNativeValidation` should be true by default, and the `valid` prop should be ignored when `useNativeValidation` is true.

**Comment by tychenjiajun** [comment] 2020-01-16 05:56
Close as WONTFIX

**Closed by tychenjiajun** 2020-01-16 05:56 UTC
Labels: bug
