### ISSUE TITLE
Issues importing styles

### ISSUE THREAD

**Issue by ktmellow** [matsp/material-components-vue#237] opened 2019-05-14 23:36 UTC
**Describe the bug**
Issues getting started with components on existing app. I'm switching from Vuetify library to this adapter library. 

**Error log:** Module build failed (from ../node_modules/sass-loader/lib/loader.js):
^
      File to import not found or unreadable: material-components-vue/dist/button/styles.

**To Reproduce**
Following the Import Components Guide:

**Vue file:**
```
<template>
<m-button @click="make" theming="primary-bg" :disabled="editing">New</m-button>
</template>
<script>
import Button from 'material-components-vue/dist/button'
Vue.use(Button)
...

</script>
<style lang="scss" scoped>
@import "material-components-vue/dist/button/styles";
</style>
```
**Webpack**:
```
module: {
  rules: [
    ...
    {
        test: /\.scss$/,
        use: [
          'vue-style-loader',
          'css-loader',
          {
            loader: 'sass-loader',
            options: {
              includePaths: ['./node_modules/@material'],
              data: '@import "./src/universal/vars.scss";',
            },
          },
        ],
      },]
}
```
**Expected behavior**
To build webpack without error using same steps as documentation.

**Comment by tychenjiajun** [comment] 2019-05-15 02:00
@ktmellow Which version of webpack, sass-loader and material-components-vue do you use?

**Comment by matsp** [comment] 2019-05-15 07:53
@ktmellow Can append the stack trace of the webpack error? Think it is more a problem of resolving the files in the webpack config.

**Comment by ktmellow** [comment] 2019-05-15 17:26
Thanks, both, for quick responses.
@tychenjiajun 
My package-lock indicates the following versions:
```
sass-loader: "7.1.0"
material-components-vue: "1.0.2"
webpack: "4.28.0"
```

@matsp Here is the full stacktrace:
```
ERROR in ./src/apps/schedule/schedule-viewer/schedule-viewer.vue?vue&type=style&index=0&id=7798617d&lang=scss&scoped=true& (../node_modules/css-loader!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/sass-loader/lib/loader.js??ref--3-2!../node_modules/vue-loader/lib??vue-loader-options!./src/apps/schedule/schedule-viewer/schedule-viewer.vue?vue&type=style&index=0&id=7798617d&lang=scss&scoped=true&)
Module build failed (from ../node_modules/sass-loader/lib/loader.js):


^
      File to import not found or unreadable: material-components-vue/dist/button/styles.
      in /app/client/src/apps/schedule/schedule-viewer/schedule-viewer.vue (line 189, column 1)
 @ ./src/apps/schedule/schedule-viewer/schedule-viewer.vue?vue&type=style&index=0&id=7798617d&lang=scss&scoped=true& (../node_modules/vue-style-loader!../node_modules/css-loader!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/sass-loader/lib/loader.js??ref--3-2!../node_modules/vue-loader/lib??vue-loader-options!./src/apps/schedule/schedule-viewer/schedule-viewer.vue?vue&type=style&index=0&id=7798617d&lang=scss&scoped=true&) 4:14-360
 @ ./src/apps/schedule/schedule-viewer/schedule-viewer.vue?vue&type=style&index=0&id=7798617d&lang=scss&scoped=true&
 @ ./src/apps/schedule/schedule-viewer/schedule-viewer.vue
 @ ../node_modules/babel-loader/lib!../node_modules/vue-loader/lib??vue-loader-options!./src/apps/schedule/schedule.vue?vue&type=script&lang=js&
 @ ./src/apps/schedule/schedule.vue?vue&type=script&lang=js&
 @ ./src/apps/schedule/schedule.vue
 @ ./src/apps/schedule/schedule.test.js
 @ ./src/test.js
```

**Comment by ktmellow** [comment] 2019-05-15 17:42
When I change my import to include .scss extension:
``
<style lang="scss" scoped>
@import "material-components-vue/dist/button/styles.scss";
</style>
``

I get an issue when that file tries to import the next file from material-components-web:
``
ERROR in ./src/apps/schedule/schedule-viewer/schedule-viewer.vue?vue&type=style&index=0&id=7798617d&lang=scss&scoped=true& (../node_modules/css-loader!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/sass-loader/lib/loader.js??ref--3-2!../node_modules/vue-loader/lib??vue-loader-options!./src/apps/schedule/schedule-viewer/schedule-viewer.vue?vue&type=style&index=0&id=7798617d&lang=scss&scoped=true&)
Module build failed (from ../node_modules/sass-loader/lib/loader.js):

@import "@material/button/mdc-button";
^
      File to import not found or unreadable: @material/button/mdc-button.
      in /app/node_modules/material-components-vue/dist/button/styles.scss (line 1, column 1)
 @ ./src/apps/schedule/schedule-viewer/schedule-viewer.vue?vue&type=style&index=0&id=7798617d&lang=scss&scoped=true& (../node_modules/vue-style-loader!../node_modules/css-loader!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/sass-loader/lib/loader.js??ref--3-2!../node_modules/vue-loader/lib??vue-loader-options!./src/apps/schedule/schedule-viewer/schedule-viewer.vue?vue&type=style&index=0&id=7798617d&lang=scss&scoped=true&) 4:14-360
 @ ./src/apps/schedule/schedule-viewer/schedule-viewer.vue?vue&type=style&index=0&id=7798617d&lang=scss&scoped=true&
 @ ./src/apps/schedule/schedule-viewer/schedule-viewer.vue
 @ ../node_modules/babel-loader/lib!../node_modules/vue-loader/lib??vue-loader-options!./src/apps/schedule/schedule.vue?vue&type=script&lang=js&
 @ ./src/apps/schedule/schedule.vue?vue&type=script&lang=js&
 @ ./src/apps/schedule/schedule.vue
 @ ./src/apps/schedule/schedule.test.js
 @ ./src/test.js
``

Does anyone have any tips for this issue since I cannot add the file extension to the dependency import?

**Comment by matsp** [comment] 2019-05-15 17:48
@ktmellow The sass-loader is not able to resolve files in the node_modules directory. Do you have your webpack config at the root of the project or in a subdirectory.

**Comment by ktmellow** [comment] 2019-05-15 18:01
My webpack is in client subdirectory. I still get the above error when I tried rebuilding with the following config with ['../node-modules/@material']:
```
module: {
  rules: [
    ...
    {
        test: /\.scss$/,
        use: [
          'vue-style-loader',
          'css-loader',
          {
            loader: 'sass-loader',
            options: {
              includePaths: ['../node_modules/@material'],
              data: '@import "./src/universal/vars.scss";',
            },
          },
        ],
      },]
}
```

**Comment by matsp** [comment] 2019-05-15 18:23
Sorry but this is all about webpack and the constellation of your directories. Your project is closed source?

**Comment by ktmellow** [comment] 2019-05-15 21:40
Yeah, closed source. Thanks for all your quick insights and time.  After your help, I was able to diagnose an absolute path that worked with my project structure. I'll leave my solution here in case this helps others getting started with the same issue.

**Project Structure from root**
```
client 
  > webpack.config.js
node_modules
server
```
**Solution in webpack config**
```
const path = require('path')
...
{
            loader: 'sass-loader',
            options: {
              includePaths: [path.resolve(__dirname, '../node_modules')],
              data: '@import "./src/universal/vars.scss";',
            },
          },
```

**Closed** 2019-05-15 21:46 UTC

**Comment by tychenjiajun** [comment] 2019-05-16 02:29
@ktmellow Thank you for your reporting! I've tried your config in my own project and can confirm that there is a mistake in the docs. I'll open a PR fixing it.

**Comment by kondasoft** [comment] 2019-07-15 14:59
@ktmellow why you have used webpack config file when VueJS recomdends 'vue.config.js'. The problem is that im still having issues making this to work with Vue Cli 3. 

Any idea how to tweak the vue.config.js file to make Vue Material to work?
