### ISSUE TITLE
@material and Vue Cli 3

### ISSUE THREAD

**Issue by alvinkonda** [matsp/material-components-vue#338] opened 2019-07-15 14:22 UTC
HI,
We need a proper guide how to set up 'Material Components Vue' with VueCli 3. Right now im importing as following: 

```
<style lang="scss">
  $mdc-theme-primary: #2196f3;
  $mdc-theme-secondary: #ff1744;
  $mdc-theme-background: #f5f5f5;
  @import "~material-components-vue/dist/theme/styles";
  @import "~material-components-vue/dist/button/styles";
  @import "~material-components-vue/dist/card/styles";
</style>
```

but i get an error:

```
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
@import "@material/theme/mdc-theme";
       ^
      Can't find stylesheet to import.
```

So how can we import 'material' with the latest VueCli 3?

Thanks
Alvin

**Comment by tychenjiajun** [comment] 2019-07-15 14:52
Duplicate of #237 

@matsp  This issue is fixed in #239 but doesn't show in VuePress docs.

**Comment by kondasoft** [comment] 2019-07-15 15:06
Well we need a proper guide. We are not all masters in VueJS. I need to know how can i edit 'vue.config.js' to make this working. Thanks

**Comment by tychenjiajun** [comment] 2019-07-15 15:12
@kondasoft See [css.loaderOptions](https://cli.vuejs.org/config/#css-loaderoptions) in vue cli docs.

**Comment by kondasoft** [comment] 2019-07-15 15:17
An example would be much appreciated. This does not seem to work

```
const path = require('path')

module.exports = {
  css: {
    loaderOptions: {
      sass: {
        includePaths: [path.resolve(__dirname, './node_modules/@material')]
      }
    }
  }
}
```

**Comment by tychenjiajun** [comment] 2019-07-15 15:21
@kondasoft [Switch by Kava-Labs](https://github.com/Kava-Labs/switch/blob/master/vue.config.js) has a great practice of using customized material-components-vue. Check it out and see line 82 to line 95 of their vue.config.js

**Comment by kondasoft** [comment] 2019-07-15 15:22
Sorry manage to solve with this:

```
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        includePaths: ['./node_modules']
      }
    }
  }
}
```

**Comment by tychenjiajun** [comment] 2019-07-15 15:28
@kondasoft Never mind.

@matsp I'll keep this issue open until the docs updated.

**Comment by ieixua** [comment] 2019-11-20 13:54
In case it serves anyone, with the latest version of vue-cli that includes sass-loader 8.0.0 (and some options are obsolete) what you have to write in the file vue.config.js is: 

```
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        sassOptions: {
          includePaths: ["./node_modules"]
        }
      }
    }
  }
};
```

**Comment by tychenjiajun** [comment] 2020-02-22 08:32
related: https://github.com/material-components/material-components-web/issues/4933

**Closed by tychenjiajun** 2020-02-22 08:32 UTC
Labels: docs
